### ISSUE TITLE
Unable to change volume levels

### ISSUE THREAD

**Issue by EnigmaNL** [GozerBlackCat/FO4ME#1]
I just installed this mod pack yesterday and so far I'm really liking it. One thing is bothering me though and that is the inability to change volume levels for individual items like footsteps, music and radio.

In-game you can only change the master audio level. I've gone through all the ini files I could find and tried to set the levels to what I wanted but nothing works.

How can I change the volume levels with this mod pack installed?

**Comment by GozerBlackCat** [comment]
By you closing the issue I assume you found the Persistent Volume Sliders MCM. In any case, I just barely managed to see this because my email notifies me. I pay much more attention to my discord, so any questions may get answers faster if posted there.

**Comment by EnigmaNL** [comment]
Yeah sorry, I found the Persistent Volume Sliders and then I closed the issue!
